apiVersion: v1
kind: Service
metadata:
  name: yash-postgres
  labels:
    app: yash-postgres
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: yash-postgres
    tier: postgres
